---
name: Setup gear
description: Setup gear
inputs:
  token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6.2.0
      with:
        go-version: '1.25'
    - uses: go-task/setup-task@v1
