version: '3'

vars:
  REPO_MODE: n/a  # n/a, ro, rw
  IMAGE: orglang/app
  CID:
    sh: >-
      find ../adt .
      -name "*.go" -exec md5sum {} + -o
      -name "Dockerfile" -exec md5sum {} +
      | LC_ALL=C sort -k 2
      | md5sum
      | head -c 7

tasks:
  binary:
    aliases: [bin, build]
    cmd: go build -o orglang main.go

  process:
    aliases: [proc, run]
    cmds:
      # -g 'useUnderlyingTypeMethods yes'
      # -g 'output:file ./generated.go'
      - go run github.com/jmattheis/goverter/cmd/goverter gen ../...
      - go run main.go

  package:
    aliases: [image, pack]
    status:
      - docker image inspect {{.IMAGE}}:{{.CID}}
    cmds:
      - task: :image:clean
        vars:
          IMAGE_KEY: "{{.IMAGE}}"
      - task: :image:build
        vars:
          IMAGE_HOME: app
          IMAGE_CTX: ..
          IMAGE_NAME: "{{.IMAGE}}"
          IMAGE_TAG: "{{.CID}}"
